# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"